import { defineConfig, globalIgnores } from 'eslint/config'
import nextVitals from 'eslint-config-next/core-web-vitals'
import nextTs from 'eslint-config-next/typescript'
import tseslint from 'typescript-eslint'
import sonarjs from 'eslint-plugin-sonarjs'

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    '.next/**',
    'out/**',
    'build/**',
    'next-env.d.ts',
    // Vendored tooling, not application code — linting it buries our own
    // findings under thousands of third-party ones.
    '.claude/**',
    // Generated by `test:coverage`; its bundled HTML report ships its own JS.
    'coverage/**',
  ]),
  {
    // A leading underscore already means "deliberately unused" throughout this codebase:
    // params that exist to satisfy a base-class signature (`getFileExcerpt(_budget)`),
    // and the omit-by-destructuring idiom (`const { clients: _clients, ...post } = typed`).
    // The rule did not know the convention, so it warned on correct code and the noise
    // made the genuine findings easy to miss. Teach it the convention rather than edit
    // seven call sites that are each doing the right thing. Anything unused *without*
    // the underscore still warns, which is the part worth keeping.
    rules: {
      '@typescript-eslint/no-unused-vars': [
        'warn',
        {
          argsIgnorePattern: '^_',
          varsIgnorePattern: '^_',
          caughtErrorsIgnorePattern: '^_',
          destructuredArrayIgnorePattern: '^_',
        },
      ],
    },
  },
  {
    // Type-aware rules. `eslint-config-next/typescript` builds on typescript-eslint's
    // `recommended`, which never reads types — so ESLint was blind to the one bug class
    // this app is most exposed to: a promise nobody awaited. `tsc` does not catch it
    // either (a dropped promise is well-typed), and vitest cannot see it, so until now
    // nothing in `npm run check` could. Server actions, cron routes and the Konva
    // exporter all fail silently when it happens.
    //
    // Scoped to `src/` because these rules need a TypeScript program: `scripts/*.mjs`
    // and the config files are not in one, and would error rather than lint.
    files: ['src/**/*.{ts,tsx}'],
    languageOptions: {
      parser: tseslint.parser,
      parserOptions: { projectService: true, tsconfigRootDir: import.meta.dirname },
    },
    plugins: { '@typescript-eslint': tseslint.plugin },
    rules: {
      '@typescript-eslint/no-floating-promises': 'error',
      '@typescript-eslint/await-thenable': 'error',
      '@typescript-eslint/no-misused-promises': [
        'error',
        // `onClick={async () => …}` is idiomatic React and safe here: the handler owns its
        // try/catch and React ignores the return value. Checking attributes would flag 25
        // correct call sites to buy nothing. The categories left on are the ones that
        // actually break — a promise used as a boolean (always truthy), a promise passed
        // where void was expected, and an async function stored in a void-typed variable.
        { checksVoidReturn: { attributes: false } },
      ],
      // NOT enabled: `require-await`. Its 26 hits were almost all async methods that exist
      // to satisfy an interface — test doubles for Supabase's thenable builder, and
      // `FileSource.fetch` implementing a base signature. Same situation as the underscore
      // convention above: the rule does not know the pattern, and the pattern is correct.
    },
  },
  {
    // SonarJS is the same analyzer SonarQube runs for JS/TS, as an ESLint plugin — so we get
    // its findings without a server to host or a per-line-of-code subscription to buy.
    //
    // Its `recommended` preset is 269 rules and fired 797 times here, almost all style
    // opinions this codebase has already decided against (405 `prefer-read-only-props`,
    // 146 `no-nested-conditional`), plus `void-use`, which would contradict the `void`
    // idiom the floating-promise rule above requires. A preset that noisy trains people to
    // ignore it. What is enabled instead is the subset that finds bugs rather than tastes,
    // measured one by one against this repo.
    files: ['src/**/*.{ts,tsx}'],
    plugins: { sonarjs: sonarjs.configs.recommended.plugins.sonarjs },
    settings: sonarjs.configs.recommended.settings,
    rules: {
      // Each of these found something real on the first run, or is free insurance at zero
      // current cost — the duplication pair below both report 0, which independently
      // confirms the 0.13% jscpd measurement that made a Sonar subscription unnecessary.
      'sonarjs/no-all-duplicated-branches': 'error',
      'sonarjs/no-identical-expressions': 'error',
      'sonarjs/no-identical-functions': 'error',
      'sonarjs/no-use-of-empty-return-value': 'error',
      'sonarjs/no-misleading-array-reverse': 'error',
      'sonarjs/link-with-target-blank': 'error',
      // NOT enabled: `different-types-comparison`. It flagged six `x !== null` guards as
      // "always true" on state that is genuinely `useState<number | null>(null)` — the
      // narrowing defeats it. A rule that calls correct null checks dead is worse than no
      // rule, because the fix it asks for is to delete the guard.
      //
      // NOT enabled: `no-alphabetical-sort` (23), `slow-regex` (15), `no-hardcoded-passwords`
      // (4, all password *form fields*), `code-eval` and `hardcoded-secret-signatures` (test
      // fixtures asserting that `javascript:` URLs are blocked). Each needs a human verdict
      // per site, which is a review, not a gate.
    },
  },
])

export default eslintConfig
