// ---- Generate ----

export interface Theme {
  description: string
  postCount: number
  isPriority: boolean
  priorityBrief?: string
  targetDate?: string
  researchUsed?: boolean
}

export interface PriorityPost {
  title: string
  brief: string
  platform: string
  targetDate: string
}

export interface GeneratePostRequest {
  clientId: string
  platform: string
  themes: Theme[]
  postType: 'single' | 'carousel' | 'reels'
  slideCount?: number
  selectedPillars: string[]
  priorityPosts?: PriorityPost[]
}

export interface CarouselSlide {
  slide_number: number
  slide_role: 'cover' | 'content' | 'value' | 'cta'
  headline: string
  body: string
  cta_text: string | null
  design_note: string
}

export interface ReelsScript {
  hook: string
  main_points: string[]
  cta: string
  on_screen_text: string[]
  visual_directions: string[]
  estimated_seconds: number
}

export interface QualityScores {
  human_score: number
  hook_score: number
  cta_score: number
  issues: Array<{ type: string; description: string }>
}

export interface CarouselQuality {
  overall_pass: boolean
  slides_passing: number
  slides_total: number
  slides: Array<{
    slide_number: number
    status: 'pass' | 'warn' | 'fail'
    scores: { specificity: number; hook_strength: number; info_density: number }
    issues: Array<{ rule: string; problem: string; suggestion: string }>
  }>
}

export interface LanguageValidation {
  passes: boolean
  naturalness_score: number
  issues: Array<{
    type: 'anglicism' | 'calque' | 'grammar' | 'formality' | 'register'
    original_text: string
    issue_description: string
    suggested_fix: string
  }>
  corrected_text: string | null
}

export interface SlopDetection {
  reads_as_human: boolean
  ai_tells_found: string[]
  worst_offending_phrase: string | null
  human_authenticity_score: number
}

export interface GeneratedPost {
  theme: string
  platform: string
  postType: 'single' | 'carousel' | 'reels'
  caption: string
  slides?: CarouselSlide[]
  reelsScript?: ReelsScript
  qualityScores?: QualityScores
  carouselQuality?: CarouselQuality
  languageValidation?: LanguageValidation
  slopDetection?: SlopDetection
  isPriority: boolean
}

export interface GeneratePostResponse {
  posts: GeneratedPost[]
  errors?: string[]
}

// ---- Clients ----

export interface CreateClientRequest {
  name: string
  niche: string
  language: string
  postsPerWeek: number
  tone: string
  targetAudience: string[]
  contentPillars: string[]
  avoidTopics: string
  clientTestimonialVoice: string
  recommendedPlatforms: string[]
  defaultPostType: string
  defaultCarouselSlides: number
  weeklyMixJson: { carousel: number; single: number }
  languageFormality: string
  isHealthNiche: boolean
  autoGenerateDay: string
  autoGenerateTime: string
  isScheduleActive: boolean
}

export interface UpdateClientRequest extends Partial<CreateClientRequest> {}

// ---- Onboarding ----

export interface OnboardRequest {
  answers: {
    q1: string
    q2: string
    q3: string
    q4: string
    q4b: string
    q5: string
    q6: string
  }
}

export interface OnboardResponse {
  niche: string
  niche_reasoning: string
  target_audience: string[]
  social_goals: string[]
  content_pillars: string[]
  content_pillars_reasoning: string
  tone: string
  avoid_topics: string
  client_testimonial_voice: string
  recommended_platforms: Array<{ platform: string; priority: string; reason: string }>
  platform_reasoning: string
  is_health_niche: boolean
  suggested_post_frequency: string
  language: string
  language_formality: string
}

// ---- Research ----

export interface ResearchRequest {
  niche: string
  language: string
}

export interface ResearchFinding {
  finding: string
  suggested_theme: string
}

export interface ResearchResponse {
  findings: ResearchFinding[]
}

// ---- Pillars ----

export interface PillarsRequest {
  niche: string
  clientId?: string
}

export interface PillarsResponse {
  pillars: Array<{ pillar: string }>
}

// ---- Best Time ----

export interface BestTimeRequest {
  clientId: string
}

export interface BestTimeWindow {
  time: string
  label: string
  reason: string
}

export interface BestTimePlatform {
  platform: string
  best_days: string[]
  best_time_windows: BestTimeWindow[]
  avoid: string
  confidence: 'research-backed' | 'ai-derived'
  reasoning_summary: string
}

export interface BestTimeResponse {
  platforms: BestTimePlatform[]
  upgrade_note: string
}

// ---- Approval ----

export interface SendApprovalRequest {
  postId: string
  clientEmail: string
}

export interface ApprovalResponse {
  status: 'approved' | 'changes_requested'
  clientNote?: string
}

// ---- Reports ----

export interface ReportRequest {
  clientId: string
  periodStart: string
  periodEnd: string
  format: 'json' | 'pdf'
}

// ---- Intelligence ----

export interface IntelligenceResponse {
  platform_updates: string[]
  niche_trends: Array<{ niche: string; trend: string; action: string }>
  weekly_tip: string
  action_nudge: string
  sources: string[]
}

// ---- API error ----

export interface ApiError {
  error: string
  code?: string
}
