import { mkdir, writeFile } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'
import { join } from 'node:path'

/**
 * Regenerate the baked default-kit fonts. Downloads the latin + cyrillic subsets of the baked
 * families from Google Fonts (variable weight ranges) into public/fonts and rewrites baked-fonts.css.
 * Run from anywhere: `node scripts/bake-fonts.mjs`. The cyrillic subset carries the Bulgarian locl
 * forms. Keep the CSS_URL weight ranges in sync with DEFAULT_TOKENS.
 */
const REPO = fileURLToPath(new URL('..', import.meta.url))
const FONTS_DIR = join(REPO, 'public/fonts')
const CSS_OUT = join(REPO, 'src/lib/renderer/baked-fonts.css')
const UA =
  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36'
const CSS_URL =
  'https://fonts.googleapis.com/css2?family=Source+Sans+3:wght@400..600&family=Source+Serif+4:wght@600..700&display=block'

const slug = (s) => s.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '')
const WANTED = new Set(['latin', 'cyrillic'])

const css = await (await fetch(CSS_URL, { headers: { 'User-Agent': UA } })).text()
await mkdir(FONTS_DIR, { recursive: true })

const blockRe = /\/\*\s*([\w-]+)\s*\*\/\s*@font-face\s*{([^}]*)}/g
const out = []
let m
let count = 0
while ((m = blockRe.exec(css))) {
  const subset = m[1]
  if (!WANTED.has(subset)) continue
  const body = m[2]
  const family = /font-family:\s*'([^']+)'/.exec(body)[1]
  const weight = /font-weight:\s*([^;]+);/.exec(body)[1].trim()
  const url = /src:\s*url\(([^)]+)\)/.exec(body)[1]
  const range = /unicode-range:\s*([^;]+);/.exec(body)[1]
  const file = `${slug(family)}-${subset}.woff2`
  const buf = Buffer.from(await (await fetch(url, { headers: { 'User-Agent': UA } })).arrayBuffer())
  await writeFile(join(FONTS_DIR, file), buf)
  count++
  out.push(
    `/* ${family} · ${subset} · wght ${weight} */\n@font-face {\n  font-family: '${family}';\n  font-style: normal;\n  font-weight: ${weight};\n  font-display: block;\n  src: url('/fonts/${file}') format('woff2');\n  unicode-range: ${range};\n}`
  )
}

const header = `/* Baked default kit fonts — Source Sans 3 (body) + Source Serif 4 (display).\n   latin + cyrillic subsets only; cyrillic carries the Bulgarian locl forms.\n   Variable weight ranges. Generated by scripts/bake-fonts.mjs; both families are SIL OFL 1.1. */\n`
await writeFile(CSS_OUT, header + '\n' + out.join('\n\n') + '\n')
console.log(`wrote ${count} woff2 files to public/fonts and baked-fonts.css`)
