export const REWRITE_SCORE_THRESHOLD = 7
export const AUTHENTICITY_URGENT_THRESHOLD = 6
export const LANGUAGE_PASS_THRESHOLD = 8
export const NGRAM_SIZE = 3
export const ANGLE_SIMILARITY_THRESHOLD = 0.15
